image: alpine/latest
packages:
  - rust
  - cargo
sources:
  - git@git.sr.ht:~ragreener1/hashable_weak
triggers:
  - action: email
    condition: failure
    to: ~ragreener1/public-inbox@lists.sr.ht
secrets:
  - 60919306-69a2-4760-8001-1a12c14454ab
tasks:
  - compile: |
      cd hashmap_union
      cargo build
  - test: |
      cd hashmap_union
      cargo test